apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name}-config
  namespace: ${namespace}
data:
  valkey.conf: |
    cluster-enabled ${cluster_enabled:yes}
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    dir /data
    port ${port:6379}
    bind 0.0.0.0
    protected-mode no
    maxmemory ${maxmemory:0}
    maxmemory-policy ${maxmemory_policy:noeviction}
