apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    app: ${name}
spec:
  selector:
    app: ${name}
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}-headless
  namespace: ${namespace}
  labels:
    app: ${name}
spec:
  clusterIP: None
  selector:
    app: ${name}
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
